from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from datetime import datetime


def set_heading_color(paragraph, hex_color):
    for run in paragraph.runs:
        run.font.color.rgb = RGBColor.from_string(hex_color)


def add_colored_line(doc, color_hex='0077B6'):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(6)
    pPr = p._p.get_or_add_pPr()
    pBdr = doc.element.makeelement(qn('w:pBdr'), {})
    bottom = doc.element.makeelement(qn('w:bottom'), {
        qn('w:val'): 'single',
        qn('w:sz'): '4',
        qn('w:space'): '1',
        qn('w:color'): color_hex,
    })
    pBdr.append(bottom)
    pPr.append(pBdr)


def build_digest(papers, github_repos, news_articles, top_pick_idx):
    doc = Document()

    # ── HEADER ─────────────────────────────
    section = doc.sections[0]
    header = section.header
    header.paragraphs[0].text = "📡 Team ResearchRadar"

    # ── FOOTER ─────────────────────────────
    footer = section.footer
    footer.paragraphs[0].text = f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}"

    # ── MARGINS ────────────────────────────
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)

    # ── TITLE ──────────────────────────────
    title_para = doc.add_heading('📡 ResearchRadar Weekly Digest', level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_heading_color(title_para, '0D1B2A')

    week_str = datetime.now().strftime('%B %d, %Y')
    sub = doc.add_paragraph(
        f'Week of {week_str}   |   {len(papers)} Papers   |   {len(github_repos)} Repos'
    )
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.color.rgb = RGBColor(100, 116, 139)
    sub.runs[0].font.size = Pt(11)

    add_colored_line(doc, '00B4D8')
    doc.add_paragraph()

    # ── TOP PICK ───────────────────────────
    top_heading = doc.add_heading('⭐ Top Pick This Week', level=1)
    set_heading_color(top_heading, '0077B6')

    if papers:
        top = papers[top_pick_idx]

        tp_title = doc.add_paragraph(top.get('title', 'No title'))
        tp_title.runs[0].bold = True
        tp_title.runs[0].font.size = Pt(12)

        tp_sum = doc.add_paragraph(top.get('summary', 'Summary not available'))
        tp_sum.runs[0].font.size = Pt(11)

        tp_link = doc.add_paragraph()
        run = tp_link.add_run(f"Read more: {top.get('link', '')}")
        run.font.color.rgb = RGBColor(0, 119, 182)

    add_colored_line(doc, '00B4D8')
    doc.add_paragraph()

    # ── PAPERS ─────────────────────────────
    papers_heading = doc.add_heading('📡 ArXiv Papers This Week', level=1)
    set_heading_color(papers_heading, '0077B6')

    for i, paper in enumerate(papers):
        p_title = doc.add_heading(f"{i+1}. {paper.get('title', 'No title')}", level=2)
        set_heading_color(p_title, '0D1B2A')

        if paper.get('authors'):
            auth_para = doc.add_paragraph(f"Authors: {paper.get('authors')}")
            auth_para.runs[0].font.size = Pt(10)
            auth_para.runs[0].italic = True

        summary_para = doc.add_paragraph(paper.get('summary', 'Not available'))
        summary_para.runs[0].font.size = Pt(11)

        link_para = doc.add_paragraph()
        link_run = link_para.add_run(f"📡 {paper.get('link', '')}")
        link_run.font.color.rgb = RGBColor(0, 119, 182)

        doc.add_paragraph()

    # ── GITHUB (TABLE VERSION 🔥) ──────────
    add_colored_line(doc, '00B4D8')
    gh_heading = doc.add_heading('📡 Trending GitHub Repos', level=1)
    set_heading_color(gh_heading, '0077B6')

    table = doc.add_table(rows=1, cols=3)
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = "Repository"
    hdr_cells[1].text = "Stars"
    hdr_cells[2].text = "Description"

    for repo in github_repos:
        row_cells = table.add_row().cells
        row_cells[0].text = repo.get('name', '')
        row_cells[1].text = str(repo.get('stars', 0))
        row_cells[2].text = repo.get('description', '')

    doc.add_paragraph()

    # ── NEWS ───────────────────────────────
    add_colored_line(doc, '00B4D8')
    news_heading = doc.add_heading('📡 AI News Headlines', level=1)
    set_heading_color(news_heading, '0077B6')

    for article in news_articles[:8]:
        n_para = doc.add_paragraph(style='List Bullet')
        run = n_para.add_run(article.get('title', ''))
        run.font.size = Pt(11)

    # ── FOOTER NOTE ────────────────────────
    doc.add_paragraph()
    add_colored_line(doc, 'CCCCCC')
    footer_para = doc.add_paragraph(
        f'Generated by ResearchRadar | OpenClaw Hackathon 2026'
    )
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_para.runs[0].font.size = Pt(9)

    # ── SAVE ──────────────────────────────
    filename = f'ResearchRadar_{datetime.now().strftime("%Y%m%d")}.docx'
    doc.save(filename)
    print(f'DOCX saved: {filename}')
    return filename